since: 2021

menu:
  - name: 随笔
    url: /essay.html
  - name: 归档
    url: /archives.html
  - name: 友链
    url: /friends.html
  - name: 留言
    url: /messages.html
  - name: 关于
    url: /about.html

waline:
  serverURL: https://waline.luckyzh.cn/