since: 2021

menu:
  - name: 随笔
    url: /essay/
  - name: 归档
    url: /archives/
  - name: 友链
    url: /friends/
  - name: 留言
    url: /messages/
  - name: 关于
    url: /about/

page:
  contents: 目录
  tags: 标签
  tagcloud: 标签云

user:
  avatar: avatar.jpg
  name: haizou
  intro: 一介凡人
  

socialLink:
  github: https://github.com/hai-zou
  email: zou.hai@outlook.com
  rss: https://luckyzh.cn/rss.xml

waline:
  serverURL: https://waline.luckyzh.cn/

algolia:
  appId: "A6S1DCIE2I"
  apiKey: "ddcd005e9001a4d845451373d4460827"
  indexName: "luckyzh"