since: 2021

menu:
  - name: 随笔
    url: /essay/
  - name: 归档
    url: /archives/
  - name: 友链
    url: /friends/
  - name: 留言
    url: /messages/
  - name: 关于
    url: /about/

page:
  contents: 目录

user:
  avatar: avatar.jpg
  intro: 一介凡人

waline:
  serverURL: https://waline.luckyzh.cn/

algolia:
  appId: "A6S1DCIE2I"
  apiKey: "ddcd005e9001a4d845451373d4460827"
  indexName: "luckyzh"